apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sGpuWorkloadResources
metadata:
  name: require-gpu-workload-resources
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    exemptImages:
      - "nvidia/dcgm-exporter:*"