apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sGpuNodeTargeting
metadata:
  name: require-gpu-node-affinity-key
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    nodeLabelKey: "nvidia.com/gpu.product"
