module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: true,
      items: [
        'intro', 
      ]
    },
    {
      type: 'category',
      label: 'General',
      collapsed: true,
      items: [          
        'allowedrepos',
        'automount-serviceaccount-token',
        'block-endpoint-edit-default-role',
        "block-loadbalancer-services",
        'block-nodeport-services',
        'block-wildcard-ingress',
        'containerlimits',
        'containerrequests',
        'containerresourceratios',
        'containerresources',
        'disallowanonymous',
        'disallowedtags',
        'externalip',
        'httpsonly',
        'imagedigests',
        'noupdateserviceaccount',
        'poddisruptionbudget',
        'replicalimits',
        'requiredannotations',
        'requiredlabels',
        'requiredprobes',
        'storageclass',
        'uniqueingresshost',
        'uniqueserviceselector',
      ],
    },
    {
      type: 'category',
      label: 'Pod Security Policy',
      collapsed: true,
      items: [
        'pspintro',
        'allow-privilege-escalation',
        'apparmor',
        'capabilities',
        'flexvolume-drivers',
        'forbidden-sysctls',
        'fsgroup',
        'host-filesystem',
        'host-namespaces',
        'host-network-ports',
        'privileged-containers',
        'proc-mount',
        'read-only-root-filesystem',
        'seccomp',
        'selinux',
        'users',
        'volumes',
      ],
    },
  ],
};
